services:
  backend:
    build:
      context: ./backend
    container_name: api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: nextjs
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
