from typing import Dict, List

experience: Dict[str, List[str]] = {
    "Junior": ["junior", "jun"],
    "Mid": ["mid", "middle", "midle", "regular"],
    "Senior": ["senior", "lead", "sen", "c-level"],
}

locations: Dict[str, List[str]] = {
    "Warszawa": ["Warsaw", "Warszawa"],
    "Kraków": ["Krakow", "Kraków"],
    "Wrocław": ["Wroclaw", "Wrocław"],
    "Poznań": ["Poznan", "Poznań"],
    "Gdańsk": ["Gdansk", "Gdańsk"],
    "Szczecin": ["Szczecin, szczecin"],
    "Łódź": ["Lodz", "Łódź"],
    "Rzeszów": ["Rzeszow", "Rzeszów"],
    "Katowice": ["Katowice"],
    "Kielce": ["Kielce"],
    "Opole": ["opole", "Opole"],
}


# input should be normalized to lowercase
technologies: Dict[str, List[str]] = {
    "JavaScript": [
        "javascript",
        "js",
        "node.js",
        "nodejs",
        "express.js",
        "expressjs",
    ],
    "Python": [
        "python",
        "python 3",
        "py",
        "pytest",
        "pyqt",
        "pyqt5",
        "pytorch",
        "pandas",
        "numpy",
        "tensorflow",
        "keras",
        "scikit-learn",
    ],
    "React": ["React", "React.js", "reactjs"],
    "Django": ["Django", "django"],
    "Flask": ["Flask", "flask"],
    "FastAPI": ["fastapi"],
    "Docker": ["docker"],
    "RESTAPI": ["restapi", "rest", "api", "restful api"],
    "Git": ["git", "github", "gitlab", "gitflow", "github actions"],
    "SQL": [
        "sql",
        "mysql",
        "postgresql",
        "sqlite",
        "mssql",
        "mariadb",
        "oracle",
        "microsft sql server",
        "sqlalchemy",
        "sql server",
        "bazy danych",
        "database",
    ],
    "Linux": ["linux", "ubuntu", "debian", "centos", "redhat", "bash", "linux kernel"],
    "GraphQL": ["graphql"],
    "Java": [
        "java",
        "java 8",
        "java 11",
        "java 14",
        "java 15",
        "kotlin/java",
        "java/kotlin",
    ],
    "Spring": ["spring", "spring boot", "spring framework"],
    "React": ["react", "react.js", "reactjs", "react native"],
    "HTML": ["html", "html5/css3", "html5"],
    "CSS": ["css", "css3", "html5/css3"],
    "TypeScript": ["typescript", "ts"],
    "Vue.js": ["vue.js", "vuejs", "vue"],
    "Angular": ["angular", "angular.js", "angularjs", "angular 2+", "angular 4"],
    "AWS": ["aws", "amazon web services", "amazon aws"],
    "Azure": ["azure", "microsoft azure"],
    "C#": [
        "c#",
        "csharp",
        "c sharp",
        "c-sharp",
        ".net",
        "net",
        "asp.net",
        "aspnet",
        "asp net",
        "asp",
        ".net core",
    ],
    "Ruby": ["ruby", "ruby on rails", "ror"],
    "PHP": ["php", "laravel", "symfony", "zend", "wordpress"],
    "NoSQL": ["nosql", "mongodb", "couchdb", "cassandra", "redis", "firebase"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Jenkins": ["jenkins"],
    "IOS": ["ios", "swift", "objective-c", "xcode"],
    "android": ["android", "kotlin", "java", "android sdk"],
    "C++": ["c++", "cpp", "c", "c++ 17"],
    "Go": ["go", "golang"],
}
